import Foundation
import Testing

@testable import AgendouCore

/// Runs every case in `Fixtures/schedule_cases.json` as its own test. Expected values in the fixture are
/// worked out by hand, never generated by the engine.
struct ScheduleCaseTests {
    @Test(arguments: ScheduleCase.all)
    func expandsLikeTheFixture(_ testCase: ScheduleCase) {
        let expansion = ScheduleEngine.expand(
            schedules: testCase.schedules, overrides: testCase.overrides, in: testCase.range)

        if let expected = testCase.expected {
            #expect(expansion.occurrences == expected)
        }
        #expect(expansion.cancelled == testCase.expectedCancelled)
        if let expectedSummary = testCase.expectedSummary {
            #expect(PeriodSummary(occurrences: expansion.occurrences) == expectedSummary)
        }
    }
}

struct ScheduleCase: Sendable, CustomTestStringConvertible {
    let name: String
    let schedules: [ScheduleVersion]
    let overrides: [Override]
    let range: Range<Int64>
    let expected: [Occurrence]?
    let expectedCancelled: [Occurrence]
    let expectedSummary: PeriodSummary?

    var testDescription: String { name }

    static let all: [ScheduleCase] = {
        let url = Bundle.module.url(forResource: "schedule_cases", withExtension: "json")!
        let raw = try! JSONDecoder().decode([RawCase].self, from: Data(contentsOf: url))
        return raw.map(ScheduleCase.init)
    }()

    private init(_ raw: RawCase) {
        // Labels ("A", "s1", "o2") become UUIDs whose order follows the labels, so the engine's
        // (start, category) ordering can be written down in the fixture.
        var labels = Set(raw.schedules.flatMap { [$0.id, $0.category] })
        labels.formUnion(raw.overrides.flatMap { [$0.id, $0.category] })
        labels.formUnion((raw.expected ?? []).map(\.category))
        labels.formUnion((raw.expectedCancelled ?? []).map(\.category))
        labels.formUnion(raw.expectedSummary?.byCategory.keys.map { $0 } ?? [])
        var ids: [String: UUID] = [:]
        for (index, label) in labels.sorted().enumerated() {
            ids[label] = UUID(uuidString: String(format: "00000000-0000-0000-0000-%012x", index + 1))!
        }

        name = raw.name
        schedules = raw.schedules.map {
            ScheduleVersion(
                id: ids[$0.id]!, categoryID: ids[$0.category]!,
                workSeconds: $0.workHours * 3_600, restSeconds: $0.restHours * 3_600,
                anchorAt: instant($0.anchorAt), startsAt: instant($0.startsAt), endsAt: $0.endsAt.map(instant))
        }
        overrides = raw.overrides.map {
            Override(
                id: ids[$0.id]!, categoryID: ids[$0.category]!, kind: $0.kind == "extra" ? .extra : .cancellation,
                startsAt: instant($0.startsAt), endsAt: instant($0.endsAt))
        }
        if let day = raw.day {
            range = CivilCalendar.interval(of: CivilDate(string: day)!)
        } else if let month = raw.month {
            range = CivilCalendar.interval(of: CivilMonth(string: month)!)
        } else {
            range = instant(raw.from!)..<instant(raw.to!)
        }
        expected = raw.expected?.map { $0.occurrence(ids) }
        expectedCancelled = (raw.expectedCancelled ?? []).map { $0.occurrence(ids) }
        expectedSummary = raw.expectedSummary.map { summary in
            PeriodSummary(
                totalSeconds: summary.hours * 3_600, count: summary.count,
                byCategory: Dictionary(
                    uniqueKeysWithValues: summary.byCategory.map { label, total in
                        (ids[label]!, PeriodSummary.Total(seconds: total.hours * 3_600, count: total.count))
                    }))
        }
    }
}

private struct RawCase: Decodable {
    struct Schedule: Decodable {
        let id: String
        let category: String
        let workHours: Int64
        let restHours: Int64
        let anchorAt: String
        let startsAt: String
        let endsAt: String?
    }

    struct Override: Decodable {
        let id: String
        let category: String
        let kind: String
        let startsAt: String
        let endsAt: String
    }

    struct Occurrence: Decodable {
        let category: String
        let startsAt: String
        let endsAt: String
        let origin: String

        func occurrence(_ ids: [String: UUID]) -> AgendouCore.Occurrence {
            let parts = origin.split(separator: ":").map(String.init)
            let origin: AgendouCore.Occurrence.Origin =
                switch parts[0] {
                case "scheduled": .scheduled(scheduleID: ids[parts[1]]!)
                case "extra": .extra(overrideID: ids[parts[1]]!)
                case "adjusted": .adjusted(overrideID: ids[parts[1]]!, scheduleID: ids[parts[2]]!)
                default: fatalError("unknown origin \(self.origin)")
                }
            return AgendouCore.Occurrence(
                categoryID: ids[category]!, startsAt: instant(startsAt), endsAt: instant(endsAt), origin: origin)
        }
    }

    struct Summary: Decodable {
        struct Total: Decodable {
            let hours: Int64
            let count: Int
        }

        let hours: Int64
        let count: Int
        let byCategory: [String: Total]
    }

    let name: String
    let schedules: [Schedule]
    let overrides: [Override]
    let day: String?
    let month: String?
    let from: String?
    let to: String?
    let expected: [Occurrence]?
    let expectedCancelled: [Occurrence]?
    let expectedSummary: Summary?

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        name = try container.decode(String.self, forKey: .name)
        schedules = try container.decodeIfPresent([Schedule].self, forKey: .schedules) ?? []
        overrides = try container.decodeIfPresent([Override].self, forKey: .overrides) ?? []
        day = try container.decodeIfPresent(String.self, forKey: .day)
        month = try container.decodeIfPresent(String.self, forKey: .month)
        from = try container.decodeIfPresent(String.self, forKey: .from)
        to = try container.decodeIfPresent(String.self, forKey: .to)
        expected = try container.decodeIfPresent([Occurrence].self, forKey: .expected)
        expectedCancelled = try container.decodeIfPresent([Occurrence].self, forKey: .expectedCancelled)
        expectedSummary = try container.decodeIfPresent(Summary.self, forKey: .expectedSummary)
    }

    private enum CodingKeys: String, CodingKey {
        case name, schedules, overrides, day, month, from, to, expected, expectedCancelled, expectedSummary
    }
}

private func instant(_ iso8601: String) -> Int64 {
    guard let date = try? Date(iso8601, strategy: .iso8601) else { fatalError("bad instant \(iso8601)") }
    return date.epochSeconds
}
