import Foundation

/// A shift as the calendar shows it.
public struct Occurrence: Hashable, Sendable {
    public enum Origin: Hashable, Sendable {
        /// Generated by a schedule version.
        case scheduled(scheduleID: UUID)
        /// Marked by hand, outside the rotation.
        case extra(overrideID: UUID)
        /// A generated occurrence replaced by an extra at the same start (cancellation + extra).
        case adjusted(overrideID: UUID, scheduleID: UUID)
    }

    public var categoryID: UUID
    public var startsAt: Int64
    public var endsAt: Int64
    public var origin: Origin

    public init(categoryID: UUID, startsAt: Int64, endsAt: Int64, origin: Origin) {
        self.categoryID = categoryID
        self.startsAt = startsAt
        self.endsAt = endsAt
        self.origin = origin
    }

    public var durationSeconds: Int64 {
        endsAt - startsAt
    }
}
